#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-rag"
compatibility_date = "2024-08-21"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "cloudflare-rag-index"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "cloudflare-rag"
database_id = "d81eb68d-95a3-45aa-8260-3e47f0ebe80a" # replace with your database id
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cloudflare-rag-bucket"
